# Generated by Django 5.2.3 on 2025-06-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('GR_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('admission_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
