# Generated by Django 5.2.3 on 2025-06-17 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Online', 'Online')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
